DBlog/urls.py
#-*- coding:utf-8 -*-
from django.contrib.auth.views import login, logout
from django.conf.urls import patterns, include, url
from DBlog.view import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DBlog.views.home', name='home'),
    #url(r'^DBlog/', include('DBlog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^DBlog/$', current_time),
    url(r'^DBlog/list/$', blog_list, name='bloglist'),
    url(r'^DBlog/archive/(?P<id>\d+)/$', getBlogById, name='detailblog'),
    url(r'^DBlog/static/(?P<path>.*)/$', 'django.views.static.serve',
         {'doucument_root':'static'}),
    url(r'^DBlog/tag/(?P<id>\d+)/$', 'blog_filter', name='filtrblog'),
    url(r'^DBlog/add/$', 'DBlog.view.blog_add', name='addblog'),
    url(r'^DBlog/del/(?P<id>\d+)/$', 'DBlog.view.blog_delete', name='delblog'),
    url(r'^DBlog/edit/(?P<id>\d+)/$', 'DBlog.view.blog_edit', name='updateblog'),
    url(r'^DBlog/comments/', include('django.contrib.comments.urls')),
    url(r'^DBlog/(?P<id>\d+)/commentshow/$', 'DBlog.view.blog_show_comment', name='showcomment'),
    
)

DBlog/models.py
#-*- coding:utf-8 -*-
'''
Created on 2013-8-3

@author: Administrator
'''
from django.db import models


class Tag(models.Model):
    '''docstring for Tags'''
    tag_name = models.CharField(max_length=20, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class Author(models.Model):
    '''docstring for Author'''
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Blog(models.Model):
    '''docstring for Blogs'''
    caption = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)
    class Meta:
        ordering = ['-publish_time']
        

DBlog/forms.py
#-*- coding:utf-8 -*-
'''
Created on 2013-8-4

@author: Administrator
'''
from django import forms

class BlogForm(forms.Form):
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)

class TagForm(forms.Form):
    tag_name = forms.CharField()

templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>
    {% block title %}
    {% endblock %}        
    </title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
	<link rel="stylesheet" href="/static/css/reset.css">
	<link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" href="/static/css/code.css">
	<script src="/static/js/modernizr.js"></script>
    <script src="/static/js/jquery-1.7.1.min.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>

<body>
    {% block body %}
        {% block header %}
            {# 任何每个页面都可能修改的文本区域的页面 #}
            {% block menu %}
            {# 你的菜单 (导航栏) 应该包含在这个区块中. 它是针对站点级的导航, 不是 每个页面专属的导航菜单. #}
            {% endblock %}
        {% endblock %}
        <div class="container">
        {% block content %}
            {# 这个区块用来放置页面正文内容. 任何页面正文内容都可能不一样. 它不 包含任何站点导航, 信息头, 页脚, 或其它任何属于 base 模板的东东. #}

            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span9">                            
                        {% block article %}
                            {% block article_title %}
                                {% comment %}
                                用来指定 content 区块的 "title". 比如 blog 的标题. 
                                也可以用来 包含 content 内的导航 (译注: 比如提纲), 或其它类似的东东. 
                                大致都是些 页面中并非主要内容的东东. 
                                我不知道这个区块是否应该放到 content tag 内, 并且对应于前面建议的 content tag, 
                                是不是还需要一个 main_content 区块.
                                {% block [section]_menu %} {% block page_menu %}
                                这是对应于之前建议的 menu 区块. 用来导航一个章节或页面.
                                {% endcomment %}
                            {% endblock %}
                            {% block article_content %}{% endblock %}
                        {% endblock %}
                        
                        {% block article_menu %} {% endblock %}
                        {% block comments %} {% endblock %}
                        </div>
                        <div class="span3">
                            {% block aside %}
                                {% block tags %}{% endblock %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            {% endblock %}
            {% block footer %}
                {# 任何每个页面都可能修改的文本区域的页脚 #}
                <p>Thanks for visiting my site! </p>
            {% endblock %}
        {% endblock %}
    </div>
    <script src="/static/js/bootstrap.min.js"></script>
</body> 
</html>

templates/blog/archive.html
{% extends "blog_base.html" %}
<!--加载comment模块-->
{% load comments %}


{% block title %} {{ blog.caption }} {% endblock %}

{% block script %}
<script type="text/javascript">
	var loadComment=function(){
		$('#comment_form form input.submit-preview').remove();
	    $('#comment_form form').submit(function() {
	        $.ajax({
	            type: "POST",
	            data: $('#comment_form form').serialize(),
	            url: "{% comment_form_target %}",
	            cache: false,
	            dataType: "html",
	            success: function(html, textStatus) {
	                $('#cmt').replaceWith(html);
	                $('#comment_form form')[0].reset();
	            },
	            error: function (XMLHttpRequest, textStatus, errorThrown) {
	                $('#comment_form form').replaceWith('Your comment was unable to be posted at this time.  We apologise for the inconvenience.');
	            }
	        });
	        return false;
	    });
	}	
	$(document).ready(function(){
		loadComment();
	});
</script>
{% endblock %}

{% block article %}
<div class="content">
	<div id="article" class="content-main">
		{% block article_title %}
		<h2>{{ blog.caption }}</h2>
		{% endblock %}
		<p class="muted">
			<i class="icon-user"></i><small> {{ blog.author }}</small>
			<i class="icon-time"></i><small> {{ blog.publish_time }}</small>
		</p>
		<section>
			{% load markup %}
			<div class="blog-content">
			{% block article_content %}{{ blog.content|markdown:'codehilite'}}{% endblock %}
			</div>
		</section>
        <div class="row-fluid post-info">
            <div class="span3">
                <p>
                <i class="icon-tag"></i>
                {% for tag in blog.tags.all %}
                <small class="muted"> {{ tag }}</small>
                {% endfor %}
                </p>
            </div>
            
            <div class="span2 offset7">
                <a href="{% url 'delblog' blog.id %}" title="delete"><i class="icon-trash"></i></a>
                <a href="{% url 'updateblog' blog.id %}" title="edit"><i class="icon-edit"></i></a>
                {% get_comment_count for blog as comment_count %}
                <a href="#cmt" title="comment"><i class=" icon-comment"></i>{{ comment_count }}</a>
            </div>
        </div>
	</div>
</div>
{% endblock %}

{% block comments %}
<div id="cmt">
    {% get_comment_count for blog as comment_count %}
        <h4 class="muted comtop">{{ comment_count }} Comments</h4>
        <hr class="soften">
    {% get_comment_list for blog as blog_com %}
    {% for comment in blog_com %}
        <div class="container-fluid none-padding">
            <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>      
            {{ comment.comment }}
        </div>
        <hr class="soften">
    {% endfor %}
</div>

<div >     
    {% get_comment_form for blog as blog_form %}  
        <div id="comment_form">
            <h4 class="muted comtop">New Comments</h4>
            <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                <fieldset>
                {% csrf_token %}
                {{ blog_form.object_pk }}
                {{ blog_form.content_type }}
                {{ blog_form.timestamp }}
                {{ blog_form.site }}
                {{ blog_form.submit_date }}
                {{ blog_form.security_hash }}
                <div class="control-group">
                    <label class="control-label" for="id_name">name: </label>
                    <div class="controls">
                        <input type="text" id="id_name" class="input-xlarge" name="name" placeholder="please enter name" required="required">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_email">email: </label>
                    <div class="controls">
                        <input class="input-xlarge" id="id_email" type="email" name="email" placeholder="please enter email" required="required">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_comment">comment: </label>
                    <div class="controls">
                        <textarea class="input-xlarge comment" id="id_comment" name="comment" placeholder="please enter comment" required="required"></textarea>
                    </div>
                </div>
                <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，那么你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>
                <div class="form-actions">
                    <input class="btn btn-info" type="submit" name="submit" value="Post">
                    {# <input class="btn btn-info" type="submit" name="preview" value="Preview"> #}
                    <input type='hidden' name='next' value="{% url 'detailblog' blog.id %}"/>
                    <!--input type='hidden' name='next' value="{% url 'showcomment' blog.id %}"/-->
                </div>
                </fieldset>
            </form> 
        </div>
</div>
{% endblock %}

templates/blog/blog_add.html
{% extends "blog_base.html" %}

{% block title %} 新建博客 {% endblock %}

{% block article %}
<form action="" method="post">
    {% csrf_token %} 
    <div class="field">
        <label for="id_caption">Title: </label>
        {% if form.caption.errors %}
        <div class="alert alert-error">
            {{ form.caption.errors }}          
        </div>
        {% endif %}
        {{ form.caption }}
    </div>
    <div class="field">        
        <label for="id_content">Content: </label>
        {% if form.content.errors %}
        <div class="alert alert-error">
            {{ form.content.errors }}
        </div>
        {% endif %}
        {{ form.content }}
    </div>
    <div class="field">
        <label for="id_tag">tags</label>
        {% if tag.tag_name.errors %}
        <div class="alert alert-error">
            {{ tag.tag_name.errors }}
        </div>
        {% endif %}
        {{ tag.tag_name }}
 	</div>
    <div class="form-actions">
        <input class="btn btn-primary" type="submit" value="save and add">
    </div>
</form>
{% endblock %}

templates/blog/blog_comments_show.html
{% load comments %}

<div id="cmt">
    {% get_comment_count for blog as comment_count %}    
        <h4 class="muted comtop">{{ comment_count }} Comments</h4>
        <hr class="soften">  
    {% get_comment_list for blog as blog_com %}
    {% for comment in blog_com %}
        <div class="container-fluid none-padding">
            <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>      
            {{ comment.comment }}           
        </div>
        <hr class="soften">                   
    {% endfor %}
</div>

templates/blog/myblog.html
{% extends "blog_base.html" %}
{% load comments %}

{% block title %} blog list {% endblock %}

{% block article %}
<article class='content-main'>
    {% for blog in blogs %}
        <h4><a href="{% url 'detailblog' blog.id %}">{{ blog.caption }}</a></h4>
        <p class="muted">
            {% for tag in blog.tags.all %}
                <i class="icon-tag"></i> <small>{{ tag }}</small>
            {% endfor %}
        </p>
        {% load markup %}
        <div>{{ blog.content|markdown:'codehilite' }} </div>

        <div class="row-fluid">
            <div class="span3">
                <p class="muted"><i class="icon-time"></i><small> {{ blog.publish_time }}</small></p>
            </div>
            <div class="span2 offset7">
                <a href="{% url 'delblog' blog.id %}" title="delete"><i class="icon-trash"></i></a>
                <a href="{% url 'updateblog' blog.id %}" title="edit"><i class="icon-edit"></i></a>
                {% get_comment_count for blog as comment_count %}
                <a href="{% url 'detailblog' blog.id %}#cmt" title="comment"><i class=" icon-comment"></i>{{ comment_count }}</a>
            </div>
        </div>
    <hr>
    {% endfor %}
</article>
{% endblock %}

{% block aside %}   

    <a class="btn" href="{% url 'addblog' %}"><i class="icon-plus"></i>写新博客</a>

    {% block tags %}
        <div class="well">
            {% for tag in tags %}
            <span class="label"><a href="{% url 'filtrblog' tag.id %}">{{ tag }}</a></span>
            {% endfor %}
        </div>
    {% endblock %}
{% endblock %}

templates/blog_base.html
{% extends "base.html" %}

{% block extra_head %}
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style> 
{% endblock %}   

{% block header %}
    {% block menu %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">  
                <a class="brand" href="#">Keily的博客</a>
                <ul class="nav">
                    <li class="active divider-vertical">
                        <a href="{% url 'bloglist' %}">我的博客</a>
                    </li>
                    <li>
                        <a href="#">关于</a>
                    </li>
                    <li>
                        <a href="#">联系我</a>
                    </li>
                </ul>                     
            </div>                
        </div>
    </div>    
    {% endblock %}
{% endblock %}